name: Build

on:
  push:
    branches: [ main ]
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]

    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache CPM packages
        uses: actions/cache@v4
        with:
          path: ~/.cpm
          key: cpm-${{ matrix.os }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: cpm-${{ matrix.os }}-

      - name: Configure
        shell: bash
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        env:
          CPM_SOURCE_CACHE: ~/.cpm

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: phantompad-${{ matrix.os }}
          archive: false
          if-no-files-found: ignore
          path: |
            build/phantompad.exe
            build/phantompad